"""client_action 의 NAVIGATE_TARGETS 를 JSON snapshot 으로 dump.

SSOT 는 백엔드 (`app/agents_v2/skills/client_actions.NAVIGATE_TARGETS`). 이 스크립트가
정규화된 JSON 으로 변환해 백엔드 + 프론트 둘 다에 commit 가능한 스냅샷을 만든다.

용도:
  - 양쪽 drift 테스트가 같은 JSON 을 SSOT 로 검증
  - 백엔드 enum 수정 시 dev 가 한 번 실행하면 두 repo 가 동기화됨

실행:
  uv run python scripts/dump_client_action_targets.py
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "app"))

from agents_v2.skills.client_actions import NAVIGATE_TARGETS  # noqa: E402

# 백엔드 commit 경로 — 백엔드 drift 테스트가 import
BACKEND_OUT = ROOT / "app" / "agents_v2" / "contract" / "client_action_targets.json"

# 프론트 repo 추정 경로 — 존재하면 같이 갱신
FRONTEND_OUT = (
    ROOT.parent.parent / "nurse_rostering_front" / "roster_front"
    / "src" / "service" / "clientActionTargets.generated.json"
)


def normalize_targets() -> dict:
    """NAVIGATE_TARGETS(set) → JSON 직렬화 가능한 dict(list, sorted)."""
    out: dict[str, dict] = {}
    for name in sorted(NAVIGATE_TARGETS):
        meta = NAVIGATE_TARGETS[name]
        out[name] = {
            "subs": sorted(meta["subs"]),
            "hn_only": bool(meta["hn_only"]),
            # adm_only: hn_only 보다 좁은 게이트(마스터 관리자 전용). 없으면 False.
            "adm_only": bool(meta.get("adm_only", False)),
        }
    return {
        "_doc": "Generated by scripts/dump_client_action_targets.py. Do not edit by hand.",
        "_source": "app/agents_v2/skills/client_actions.NAVIGATE_TARGETS",
        "targets": out,
    }


def main() -> int:
    payload = normalize_targets()
    text = json.dumps(payload, indent=2, ensure_ascii=False) + "\n"

    BACKEND_OUT.parent.mkdir(parents=True, exist_ok=True)
    BACKEND_OUT.write_text(text, encoding="utf-8")
    print(f"wrote {BACKEND_OUT.relative_to(ROOT)}")

    if FRONTEND_OUT.parent.exists():
        FRONTEND_OUT.write_text(text, encoding="utf-8")
        print(f"wrote {FRONTEND_OUT}")
    else:
        print(f"(frontend path not found: {FRONTEND_OUT} — skipping)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
